version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-net
    ports:
      - "5432:5432"

  app:
    build: .
    networks:
      - app-net
    depends_on:
      - postgres
    ports:
      - "5131:5131"
      - "5132:5132"

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16