version: "3"
services:
  app: # Ваш микросервис
    build: .
    networks: # Та же сеть
      - app-net
    ports:
      - "8082:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

networks: # Объявляем сеть
  app-net:
